name: Build & Deploy FastAPI to Cloud Run

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: maps-api-project-460015
      REGION: us-central1
      SERVICE_NAME: map-backend
      REPO: circlemaprepo
      IMAGE: us-central1-docker.pkg.dev/maps-api-project-460015/circlemaprepo/map-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --service-account github-ci@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --quiet

      - name: Get Cloud Run URL
        run: |
          gcloud run services describe $SERVICE_NAME \
            --platform managed \
            --region $REGION \
            --format='value(status.url)'
